### ISSUE TITLE
Finalizzare candidatura

### ISSUE THREAD

**Issue by ggardin** [Error-418-SWE/Documenti#14]
Questa issue ha lo scopo di tracciare i processi di revisione della documentazione richiesta per la candidatura.

---

Documentazione prodotta:
- [ ] Lettera di presentazione[^1] (#12)
- [ ] Valutazione dei capitolati[^2] (#13)
- [ ] Verbali interni
  - [ ] 17/10
  - [ ] 20/10
  - [ ] 25/10 (#9)
  - [ ] 26/10
  - [ ] 29/10
- [ ] Verbali esterni
  - [ ] 26/10

Documentazione revisionata:
- [ ] Lettera di presentazione (#12)
- [ ] Valutazione dei capitolati (#13)
- [ ] Verbali interni
  - [ ] 17/10
  - [ ] 20/10
  - [ ] 25/10 (#9)
  - [ ] 26/10
  - [ ] 29/10
- [ ] Verbali esterni
  - [ ] 26/10

Altro:
- [ ] Aggiornare readme.md

[^1]: contiene dichiarazione d'impegni, scadenza ultima di consegna, preventivo dei costi, computo ore produttive.
[^2]: riporta le motivazioni della scelta, l'elenco degli incontri esplorativi con i proponenti.
